//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dopadCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {

        }
    
        public string Id { get; set; }
        public string PostingUserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> SkillLevel { get; set; }
        public string WorkCategory { get; set; }
        public string AlternateContact { get; set; }
        public string RenumerationType { get; set; }
        public string RenumerationAmount { get; set; }
        public string ImgUrl { get; set; }
        public string Tags { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual ApplicationUser AspNetUser { get; set; }

    }
}
